-- Criação da tabela de boletos
CREATE TABLE IF NOT EXISTS `boletos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tipo_entidade` enum('aluno','polo','avulso') NOT NULL,
  `entidade_id` int(11) DEFAULT NULL,
  `nome_pagador` varchar(255) NOT NULL,
  `cpf_pagador` varchar(20) NOT NULL,
  `endereco` varchar(255) DEFAULT NULL,
  `bairro` varchar(100) DEFAULT NULL,
  `cidade` varchar(100) DEFAULT NULL,
  `uf` varchar(2) DEFAULT NULL,
  `cep` varchar(10) DEFAULT NULL,
  `descricao` varchar(255) NOT NULL,
  `valor` decimal(10,2) NOT NULL,
  `data_emissao` date NOT NULL,
  `data_vencimento` date NOT NULL,
  `data_pagamento` date DEFAULT NULL,
  `status` enum('pendente','pago','cancelado','vencido') NOT NULL DEFAULT 'pendente',
  `nosso_numero` varchar(50) DEFAULT NULL,
  `linha_digitavel` varchar(100) DEFAULT NULL,
  `codigo_barras` varchar(100) DEFAULT NULL,
  `url_boleto` varchar(255) DEFAULT NULL,
  `grupo_boletos` varchar(50) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `tipo_entidade` (`tipo_entidade`,`entidade_id`),
  KEY `status` (`status`),
  KEY `data_vencimento` (`data_vencimento`),
  KEY `grupo_boletos` (`grupo_boletos`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
